# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfHouseholdMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('preferred_phone', models.CharField(choices=[('home', 'Home'), ('mobile', 'Mobile')], max_length=20)),
                ('preferred_contact_tod', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=20)),
                ('alt_contact_first_name', models.CharField(max_length=100)),
                ('alt_contact_last_name', models.CharField(max_length=100)),
                ('alt_contact_mobile_phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20)),
                ('alt_contact_home_phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20)),
                ('alt_contact_relationship', models.CharField(choices=[('relative', 'Relative'), ('spouse', 'Spouse'), ('friend', 'Friend'), ('coworker', 'Coworker')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('county', models.CharField(max_length=100)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('home_phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20)),
                ('type_of_household', models.CharField(choices=[('single_female', 'Single parent female'), ('single_male', 'Single parent male'), ('single_person', 'Single person'), ('two_parent', 'Two parent household'), ('two_adults', 'Two adults'), ('no_children', 'No children'), ('other', 'Other')], max_length=20)),
                ('type_of_household_other', models.CharField(max_length=40)),
                ('housing', models.CharField(choices=[('apartment', 'Apartment'), ('homeless', 'Homeless'), ('homeowner', 'Homeowner'), ('housing_assistance', 'Housing assistance'), ('other', 'Other')], max_length=20)),
                ('housing_other', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(max_length=11)),
                ('mobile_phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20)),
                ('household_relationship', models.CharField(choices=[('apartment', 'Apartment'), ('homeless', 'Homeless'), ('homeowner', 'Homeowner'), ('housing_assistance', 'Housing assistance'), ('other', 'Other')], max_length=20)),
                ('household_relationship_other', models.CharField(max_length=40)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccsa_csbg_survey.Household')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMemberDemographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('education', models.CharField(choices=[('pre_hs', '0-8 grade'), ('in_hs', '9-12 no high school graduation'), ('hs_grad', 'High school graduate/GED'), ('post_hs', '12+ post sec'), ('college_degree', '2 or 4 year degree')], max_length=20)),
                ('race', models.CharField(choices=[('black', 'Black/African American'), ('white', 'White'), ('native', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('multi', 'Multi-race'), ('other', 'Other')], max_length=20)),
                ('ethnicity', models.CharField(choices=[('hispanic', 'Hispanic'), ('not_hispanic', 'Not Hispanic')], max_length=20)),
                ('no_health_insurance', models.BooleanField()),
                ('disabled', models.BooleanField()),
                ('veteran', models.BooleanField()),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccsa_csbg_survey.HouseholdMember')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMemberIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment', models.CharField(choices=[('employed', 'Employed'), ('not_employed', 'Not employed'), ('self_employed', 'Self employed')], max_length=20)),
                ('pay_period', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('semi_monthly', 'Twice a month'), ('monthly', 'Monthly'), ('other', 'Other')], max_length=50)),
                ('pay_period_other', models.CharField(blank=True, max_length=50)),
                ('other_income_cash', models.BooleanField()),
                ('other_income_snap', models.BooleanField()),
                ('other_income_tanf', models.BooleanField()),
                ('other_income_ss', models.BooleanField()),
                ('other_income_ssdi', models.BooleanField()),
                ('other_income_medicare', models.BooleanField()),
                ('other_income_other_agencies', models.BooleanField()),
                ('other_income_gifts', models.BooleanField()),
                ('other_income_unemployment', models.BooleanField()),
                ('other_income_workers_comp', models.BooleanField()),
                ('other_income_pensions', models.BooleanField()),
                ('other_income_job_training', models.BooleanField()),
                ('other_income_military_allotments', models.BooleanField()),
                ('other_income_va', models.BooleanField()),
                ('other_income_insurance', models.BooleanField()),
                ('other_income_alimony', models.BooleanField()),
                ('other_income_foster_payments', models.BooleanField()),
                ('other_income_child_support', models.BooleanField()),
                ('other_income_college_scholarship', models.BooleanField()),
                ('other_income_student_loans', models.BooleanField()),
                ('other_income_other', models.CharField(max_length=50)),
                ('no_proof_of_income', models.BooleanField()),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccsa_csbg_survey.HouseholdMember')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hear_govt_agency', models.BooleanField()),
                ('hear_united_way', models.BooleanField()),
                ('hear_radio_ad', models.BooleanField()),
                ('hear_ss_agency', models.BooleanField()),
                ('hear_internet', models.BooleanField()),
                ('hear_gccsa_client', models.BooleanField()),
                ('hear_flyer', models.BooleanField()),
                ('hear_paper_tv_ad', models.BooleanField()),
                ('hear_other', models.CharField(max_length=50)),
                ('previous_client', models.BooleanField()),
                ('gccsa_history_years', models.SmallIntegerField()),
                ('contact_reason_recent_divorce', models.BooleanField()),
                ('contact_reason_job_loss', models.BooleanField()),
                ('contact_reason_relocated', models.BooleanField()),
                ('contact_reason_housing_award', models.BooleanField()),
                ('contact_reason_eviction', models.BooleanField()),
                ('contact_reason_unexpected_expenses', models.BooleanField()),
                ('contact_reason_other', models.CharField(max_length=50)),
                ('other_services_rental_assistance', models.BooleanField()),
                ('other_services_electricity_assistance', models.BooleanField()),
                ('other_services_bus_passes', models.BooleanField()),
                ('other_services_food', models.BooleanField()),
                ('other_services_nutrition', models.BooleanField()),
                ('other_services_head_start', models.BooleanField()),
                ('other_services_vocational_training', models.BooleanField()),
                ('other_services_adult_basic_education', models.BooleanField()),
                ('other_services_financial_literacy', models.BooleanField()),
                ('other_services_housing_counseling', models.BooleanField()),
                ('other_services_job_readiness', models.BooleanField()),
                ('other_services_computer_classes', models.BooleanField()),
                ('other_services_esl', models.BooleanField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccsa_csbg_survey.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_symbol', models.CharField(db_index=True, max_length=8)),
                ('org_product', models.CharField(db_index=True, max_length=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='org',
            unique_together=set([('org_symbol', 'org_product')]),
        ),
        migrations.AddField(
            model_name='household',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccsa_csbg_survey.Org'),
        ),
        migrations.AddField(
            model_name='headofhouseholdmember',
            name='household_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gccsa_csbg_survey.HouseholdMember'),
        ),
    ]
